### ISSUE TITLE
I cann't download pictures from hitomi.la

### ISSUE THREAD

**Issue by nazhendenb** [dfkdream/Go-hitomi#1]
URL : https://hitomi.la/doujinshi/lilispa---lilith-spa!-%E6%97%A5%E6%9C%AC%E8%AA%9E-1549920.html

command：`hitomi.exe -i 1549920 -n kedama` (I have added it to $PATH and renamed it)
output:

using 4 CPU(s)
Gallery ID : 1549920
Gallery Name : kedama
Compression : true
Start HTTP Server : false
Download retry limit : 3
fetching image list
fetched 0 images
panic: runtime error: index out of range

**Comment by dfkdream** [comment]
Hi, thanks for your report :)
It seems like they changed gallery json structure.
Fixed in [Release v1.1.0](https://github.com/dfkdream/Go-hitomi/releases/tag/v1.1.0)

**Comment by nazhendenb** [comment]
> Hi, thanks for your report :)
> It seems like they changed gallery json structure.
> Fixed in [Release v1.1.0](https://github.com/dfkdream/Go-hitomi/releases/tag/v1.1.0)

Thanks for replying，but I still cann't download them

COMMAND:HitomiV1.0.exe -i 1549920 -n kedama
OUTPUT:
using 4 CPU(s)
Gallery ID : 1549920
Gallery Name : kedama
Compression : true
Start HTTP Server : false
Download retry limit : 3
fetching image list
2020/05/11 11:58:29 unexpected end of JSON input

**Comment by dfkdream** [comment]
It seems like your ISP is blocking the website. Would you like to test it with VPN or other anti-block tools?

**Comment by nazhendenb** [comment]
> It seems like your ISP is blocking the website. Would you like to test it with VPN or other anti-block tools?

I live in China and I have to use proxy to access to hitomi.la 
So I think I need use proxy such as "set http_proxy=socks5://127.0.0.1:7891"  
But I don not know how to set proxy for your script

**Comment by dfkdream** [comment]
This program does not have internal proxy support, so I think you need to setup system-wide proxy.

**Comment by dfkdream** [comment]
I added socks5 proxy support to master branch, but not tested. Try with `-socks <address>` option :)

**Comment by nazhendenb** [comment]
> I added socks5 proxy support to master branch, but not tested. Try with `-socks <address>` option :)

It seems like exe for windows x64 still not be updated. Then I tried to install it on linux Ubuntu18.04 (VPS in Japan and do not need proxy)

COMMAND:go build Go-hitomi.go

OUTPUT:
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: extracting golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
"# command-line-arguments"
./Go-hitomi.go:97:36: undefined: ImageURLFromImageInfo

**Comment by dfkdream** [comment]
Sorry, I forgot to update Readme.
You need to build it with `go build` command. (without file name)

ps) I didn't uploaded executable file because it's not been tested. if you want to use it on windows, please build it with go for windows :)

ps2) I uploaded windows binary to [v1.2.0 Pre-release](https://github.com/dfkdream/Go-hitomi/releases/tag/v1.2.0%2Bpre).

**Comment by nazhendenb** [comment]
> Sorry, I forgot to update Readme.
> You need to build it with `go build` command. (without file name)
> 
> ps) I didn't uploaded executable file because it's not been tested. if you want to use it on windows, please build it with go for windows :)
> 
> ps2) I uploaded windows binary to [v1.2.0 Pre-release](https://github.com/dfkdream/Go-hitomi/releases/tag/v1.2.0%2Bpre).

Thank you! I successed download pictures on linux. But still fail to download them on windows.

COMMAD:Go-hitomi.exe -i 1549920 -n kedama -socks 127.0.0.1:7891

OUTPUT:
using 4 CPU(s)
Gallery ID : 1549920
Gallery Name : kedama
Compression : true
Start HTTP Server : false
Download retry limit : 3
Socks5 proxy address : 127.0.0.1:7891
fetching image list
2020/05/11 13:07:58 unexpected end of JSON input

Then I tried again

COMMAND: Go-hitomi.exe -i 1549920 -n kedama -socks socks5://127.0.0.1:7891

OUTPUT:
using 4 CPU(s)
Gallery ID : 1549920
Gallery Name : kedama
Compression : true
Start HTTP Server : false
Download retry limit : 3
Socks5 proxy address : socks5://127.0.0.1:7891
fetching image list
2020/05/11 13:14:09 unexpected end of JSON input

The socks proxy port is 7891 like this
![image](https://user-images.githubusercontent.com/36919867/81526234-a66a2c00-9389-11ea-8c41-5ed58479025c.png)

**Comment by nazhendenb** [comment]
![image](https://user-images.githubusercontent.com/36919867/81526723-031a1680-938b-11ea-95b5-4220a024cbce.png)

I read README. and it seem like "-c false" can let program do not compress files, but the output is still be "Compression : true"

**Comment by dfkdream** [comment]
I forgot to apply proxy setup to json downloader. Sorry.
Please try with [v1.2.1 Pre-release](https://github.com/dfkdream/Go-hitomi/releases/tag/v1.2.1%2Bpre).

About Compression option: you need to pass `-c=false` (`=` is necessary). I don't know why, but golang's [flag](https://golang.org/pkg/flag/) library requires that :)

**Comment by nazhendenb** [comment]
Thank you, I successed download them on windows! 
![image](https://user-images.githubusercontent.com/36919867/81529803-39a75f80-9392-11ea-8094-12439b238a0e.png)

**Comment by dfkdream** [comment]
Nice to hear that :smile:
